### ISSUE TITLE
ERROR in tests with cucumber+capybara+selenium (firefox)

### ISSUE THREAD

**Issue by linuxonrails** [inem/coffee-haml-filter#2]
:coffee scripts inline HAML only give me an error in test-execution:

Internal Server Error
Error: Parse error on line 10: Unexpected 'IDENTIFIER' at Object.parseError (/usr/lib/coffee-script/lib/parser.js:472:11) at Object.parse (/usr/lib/coffee-script/lib/parser.js:548:22) at Object.compile (/usr/lib/coffee-script/lib/coffee-script.js:29:22) at /usr/lib/coffee-script/lib/command.js:149:33 at Socket.<anonymous> (/usr/lib/coffee-script/lib/command.js:181:14) at Socket.emit (events.js:61:17) at Socket._onReadable (net.js:652:51) at IOWatcher.onReadable [as callback](net.js:177:10)
WEBrick/1.3.1 (Ruby/1.9.2/2011-07-09) at 127.0.0.1:54889

**Comment by linuxonrails** [comment]
I'm sorry. It was my fault: problem with rails, not coffe/haml :-D

Please, close the issue!
